### ISSUE TITLE
头一次见到webview2的应用，想问下这跟electron区别大么？

### ISSUE THREAD

**Issue by lxfly2000** [GizmoOAO/vrchat-cache-mover#3]
想研究下

**Comment by GizmoOAO** [comment]
最大的区别就是应用本体会小很多.
如果普及的话, 多个WebView2的应用共用一个浏览器进程和一些乱七八糟的进程资源消耗也能小点.
但WebView2现在数据交互是直接传JSON的, 性能很糟糕.
现阶段做小东西挺合适的, 做正经玩意还是Electron靠谱
